/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ToolsVscodeIndexRouteImport } from './routes/tools/vscode/index'
import { Route as ToolsTerminalIndexRouteImport } from './routes/tools/terminal/index'
import { Route as ToolsQuickTakeUnsplashImageIndexRouteImport } from './routes/tools/quick-take-unsplash-image/index'
import { Route as ToolsGhosttyTerminalIndexRouteImport } from './routes/tools/ghostty-terminal/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVscodeIndexRoute = ToolsVscodeIndexRouteImport.update({
  id: '/tools/vscode/',
  path: '/tools/vscode/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTerminalIndexRoute = ToolsTerminalIndexRouteImport.update({
  id: '/tools/terminal/',
  path: '/tools/terminal/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQuickTakeUnsplashImageIndexRoute =
  ToolsQuickTakeUnsplashImageIndexRouteImport.update({
    id: '/tools/quick-take-unsplash-image/',
    path: '/tools/quick-take-unsplash-image/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsGhosttyTerminalIndexRoute =
  ToolsGhosttyTerminalIndexRouteImport.update({
    id: '/tools/ghostty-terminal/',
    path: '/tools/ghostty-terminal/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/tools/ghostty-terminal': typeof ToolsGhosttyTerminalIndexRoute
  '/tools/quick-take-unsplash-image': typeof ToolsQuickTakeUnsplashImageIndexRoute
  '/tools/terminal': typeof ToolsTerminalIndexRoute
  '/tools/vscode': typeof ToolsVscodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/tools/ghostty-terminal': typeof ToolsGhosttyTerminalIndexRoute
  '/tools/quick-take-unsplash-image': typeof ToolsQuickTakeUnsplashImageIndexRoute
  '/tools/terminal': typeof ToolsTerminalIndexRoute
  '/tools/vscode': typeof ToolsVscodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/tools/ghostty-terminal/': typeof ToolsGhosttyTerminalIndexRoute
  '/tools/quick-take-unsplash-image/': typeof ToolsQuickTakeUnsplashImageIndexRoute
  '/tools/terminal/': typeof ToolsTerminalIndexRoute
  '/tools/vscode/': typeof ToolsVscodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/tools/ghostty-terminal'
    | '/tools/quick-take-unsplash-image'
    | '/tools/terminal'
    | '/tools/vscode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/tools/ghostty-terminal'
    | '/tools/quick-take-unsplash-image'
    | '/tools/terminal'
    | '/tools/vscode'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/tools/ghostty-terminal/'
    | '/tools/quick-take-unsplash-image/'
    | '/tools/terminal/'
    | '/tools/vscode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ToolsGhosttyTerminalIndexRoute: typeof ToolsGhosttyTerminalIndexRoute
  ToolsQuickTakeUnsplashImageIndexRoute: typeof ToolsQuickTakeUnsplashImageIndexRoute
  ToolsTerminalIndexRoute: typeof ToolsTerminalIndexRoute
  ToolsVscodeIndexRoute: typeof ToolsVscodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/vscode/': {
      id: '/tools/vscode/'
      path: '/tools/vscode'
      fullPath: '/tools/vscode'
      preLoaderRoute: typeof ToolsVscodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/terminal/': {
      id: '/tools/terminal/'
      path: '/tools/terminal'
      fullPath: '/tools/terminal'
      preLoaderRoute: typeof ToolsTerminalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/quick-take-unsplash-image/': {
      id: '/tools/quick-take-unsplash-image/'
      path: '/tools/quick-take-unsplash-image'
      fullPath: '/tools/quick-take-unsplash-image'
      preLoaderRoute: typeof ToolsQuickTakeUnsplashImageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ghostty-terminal/': {
      id: '/tools/ghostty-terminal/'
      path: '/tools/ghostty-terminal'
      fullPath: '/tools/ghostty-terminal'
      preLoaderRoute: typeof ToolsGhosttyTerminalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  ToolsGhosttyTerminalIndexRoute: ToolsGhosttyTerminalIndexRoute,
  ToolsQuickTakeUnsplashImageIndexRoute: ToolsQuickTakeUnsplashImageIndexRoute,
  ToolsTerminalIndexRoute: ToolsTerminalIndexRoute,
  ToolsVscodeIndexRoute: ToolsVscodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
